### ISSUE TITLE
Crash after netsplit

### ISSUE THREAD

**Issue by TjerkNan** [minvws/rdo-journalert#6]
TZT ff type error afvangen

```
Traceback (most recent call last):
  File "/usr/local/rdo-journalert/rdo-journalert_v0.0.1/journalert/journalert", line 409, in <module>
    main()
  File "/usr/local/rdo-journalert/rdo-journalert_v0.0.1/journalert/journalert", line 402, in main
    process_log_data_from_systemd(settings, journal_reader)
  File "/usr/local/rdo-journalert/rdo-journalert_v0.0.1/journalert/journalert", line 348, in process_log_data_from_systemd
    processed_events = process_events_list(settings, events, allow_list_obj, log)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/rdo-journalert/rdo-journalert_v0.0.1/journalert/journalert", line 266, in process_events_list
    result = p.map(process_single_event, event_object_list)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by TjerkNan** [comment]
Ik heb dit issue niet kunnen reproduceren en dan is het lastig om een goede fix te maken.
Het issue ontstond omdat er een netwerk storing was bij Prolocation, maar waarom dit 'bytes-like' data veroorzaakt  ipv string is mij niet helder.

Ik zou een simpele try-except kunnen zetten om p.map(.... maar wat doen we in de exceptie --> negeren betekent dat je log regels niet parsed zonder het te weten. Crashen is dan misschien beter. 

Een for-loop met ansible om eventueel de services even te herstarten over de machines is worst-case een prima werkende oplossing.
